### ISSUE TITLE
Can overwrite an existing image without prompt on saving

### ISSUE THREAD

**Issue by tsujan** [lxqt/lximage-qt#109]
##### Expected Behavior
lximage-qt shouldn't overwrite any image without prompt while saving.

##### Current Behavior
It can overwrite without prompt when the chosen save name doesn't have any extension.

##### Possible Solution
Check for the existence of the image and show a prompt when needed.

##### Steps to Reproduce (for bugs)

1. Put an image with the name `X.png` in some folder.
2. Open another image with lximage-qt and save it with the name `X` *but without an extension* into that folder.
3. It'll be saved with the name `X.png` and will overwrite the previous image without prompt.

##### System Information

* Every LXQt component is the latest.

**Comment by igordsm** [comment]
Hello, 

I would like to take a shot at this. It seems to me that this behavior can occur only when using Save As, so I am messing with QMainWindow::saveFileName.From my brief research, QFileDialog is not able to show the "File (A) exists, Do you want to override?" dialog for file names without extension (specially since we add the extension after the dialog is closed. 

I have a partial solution working with a loop that checks if the file exists and shows a dialog only if the default extension is used. However, using this solution we would need to add extra translation strings. Is this ok?

**Comment by tsujan** [comment]
> However, using this solution we would need to add extra translation strings. Is this ok?

Yes, of course.

Sorry that I forgot this; I was/am very busy with other projects.

**Comment by igordsm** [comment]
@tsujan Thanks for the quick answer! Now for the real question: how do I update the .ts files in LXQt? I found some in lximage-qt/src/translations/lximage-qt but it seems that they are not used when building (instead the lxqt-i10n repo is downloaded and used). If I can get this working I can submit a patch in the next few days. 

PS: The [translation wiki](https://github.com/lxqt/lxqt/wiki/Translation) was not very useful since it only shows how to translate the .ts files, but not how to regenerate them...

**Comment by agaida** [comment]
@igordsm - trust me, you don't want to right now :D - But this will change soon. 
https://github.com/lxqt/lxqt/issues/1495

**Comment by agaida** [comment]
@igordsm - in short - we had messed it up in the past few years - Weblate 3.0 was released three days ago, our only problem is to merge back the translations back into a place where they belong to. Simple task, < 800 lines code needed :P

**Comment by igordsm** [comment]
@agaida So I can suppose that, if I add a new translation string it will magically appear in the .ts files?

**Comment by agaida** [comment]
right - if you read the linked thread, the main problem is to place the already finished translations in the repo again - without shooting us in both feets or knees. If that is done i will import the translations into weblate and add a script to our build tools that will do the translation updates. Something like:

```
lupdate $TRANSLATION_ROOT -ts $TRANSLATION_DIR/$SUBCOMPONENT/*.ts -locations absolute -no-sort -no-obsolete
```
in nice, easy and right :sunglasses:
