### ISSUE TITLE
Add open in external editor feature to LXImage-Qt

### ISSUE THREAD

**Issue by kenfallon** [lxqt/lximage-qt#289]
##### Expected Behavior

There should be a **open in external editor** feature under Edit > Open in External Editor and on the toolbar. 
There should also be a way to set the default editor in Edit > And a preference to set up the path to the External Editor. Under Edit > Preferences > External Editor.

##### Current Behavior

There is no **open in external editor** feature.

##### Steps to Reproduce (for bugs)

1. N//A

##### Context

When I exhaust the editing options of  LXImage-Qt I often need to edit the image in an external editor. Having a one click way to open it would be most excellent.

##### System Information

* Distribution & Version: Fedora release 30 (Thirty)
* Kernel: Linux 5.3.8-200.fc30.x86_64 x86_64 x86_64 x86_64 GNU/Linux
* Qt Version: 5.12.5
* libfm-qt Version: 0.14.1
* libqtxdg Version: 3.3.1
* lxqt-build-tools Version: 0.6.0
* Package version: 0.14.1

**Comment by Chiitoo** [comment]
I almost went for implementing something like this some time ago (I'd like to right-click the image area and 'Open With...'), but then I remembered the thumbnail area has that.  I don't usually have it visible, so it's far from optimal, but it helps at least a little bit.

**Comment by tsujan** [comment]
It seems there's only one case, where this isn't a duplicate functionality: a screenshot is taken but isn't saved yes. Otherwise, lximage-qt doesn't show a deleted image.

However, since the screenshot functionality will be removed sooner or later, this will be a duplicate ;) In LXQt, we avoid duplicate functionalities. @agaida, don't we?

In short, just press `T` and do more that opening in an editor. That's one of the advantages of using libfm-qt.

**Comment by agaida** [comment]
@tsujan - not really - if we don't want more than very basic editing functions in lximage-qt, an open in would be helpful - same kind of helpful as in screengrab. And i wouldn't see it as duplicated functionality if we do it right.

More verbose: Screengrab has some functionality to much, some needed functionality not implemented - but the base and idea is fine (erm, not implementationwise :) ) - We don't have to re-invent the wheel here, but a short look what others do could be helpful. I don't think that we should implement all the things that already are implemented in flameshot - but we could make lximage-qt to the central point of simple image editing. Lximage-qt have already cool features in that regard. Esp the upload functionality is great.

**Comment by agaida** [comment]
ok, now i get what you mean - hihihi . very intuitive ... 

Serious, such functionality should be available without activated miniatures

**Comment by tsujan** [comment]
OK. If someone makes a clean PR, I'll approve it.

Personally, I prefer more interesting jobs like https://github.com/lxqt/lximage-qt/issues/288.

**Comment by agaida** [comment]
yeah, i know - but it's fucking ugly in a possible workflow, really - not a drama, but nobody will find this really good functionality. Maybe two screenshots, and you don't want to hear the swearwords while i'm creating these ...

(will take a minute unfortunately)

**Comment by Chiitoo** [comment]
Forgot to add, that one reason to why I tend to not use the thumbnail feature (especially just for "Open With...", is the fact that the thumbnails need to be created, and it will lead to sometimes having tens of thousands of small images that serve no purpose under '$HOME/.cache/thumbnails/normal'.

I think something like 'delete thumbnails on exit' might amend that, though they're still being created.

I also wonder if it's related to PCManFM-Qt, that when saving files via, say, Falkon, thumbnails are also created even though the setting for showing thumbnails is off in PCManFM-Qt. I never remembered to look more into that. Anyblue, that's also for another issue.

**Comment by tsujan** [comment]
> and it will lead to sometimes having tens of thousands of small images that serve no purpose under '$HOME/.cache/thumbnails/normal'.

You probably don't use thumbnails with file managers either. Here, `$HOME/.cache/thumbnails` is only 414.4 MiB after years (4-5?) and there are nice commands to delete old thumbnails, although I've never used them.

Deleting thumbnails could also be done by pcmanfm-qt -- based on the date -- as an additional feature. But, you and I seem to be the only users who worry about the size of `$HOME/.cache/thumbnails` (see https://github.com/lxqt/pcmanfm-qt/issues/582). I preferred to ignore it but if it's really needed, I think the feature can be implemented.

**Comment by tsujan** [comment]
And don't forget that `$HOME/.cache/thumbnails` isn't limited to pcmanfm-qt (libfm-qt). It's somehow the standard location for saving thumbnails. The real trouble starts when some apps decide to save their thumbnails in other places.

**Comment by agaida** [comment]
a) this will happend
b) it's still happend
c( it doesn't count

having thumbs as an additional feature is a fine thing and should not be discussed - with a big but

BUT: I don't think it would be a good idea to bind the described (and current) functionality to existing thumbnails  - easy as it can be.

**Comment by tsujan** [comment]
Ah, to test it, I did a bad thing and used this to remove my thumbnails older than 3 months:
```
nice find ~/.cache/thumbnails -name "*.png" -atime +90 | xargs rm -f
```
Now, they should be created again. The reason is `noatime` in my `/etc/fstab`.

Actually, with `noatime`, it's more practical to not remove thumbnails.

> I don't think it would be a good idea to bind the described (and current) functionality to existing thumbnails - easy as it can be.

It isn't bound to existing thumbnails. When `T` is pressed, the current image will be selected and made visible (by auto-scrolling). The user doesn't need to look at thumbnails to find it.

Stopping thumbnail creation is a feature that can be added to lximage-qt but I think it's a bad idea: It's an image *viewer* after all.

**Comment by Chiitoo** [comment]
Yeah, I'm not even that concerned about the file size... well, it's a part of it probably.  Some might be concerned about writes on SSDs (I really am not, though I can say I don't compile all my packages on Gentoo on an SSD).

I think to me it's mostly just about the fact that there can be a rather big number of files laying around that I don't really make use of... ever (just removed over 15k of them, with the oldest being from March 2019 (I indeed occasionally delete them manually)).  Not very strong reasoning perhaps, and yeah, many other applications do it as well.

Was looking around, as I was almost sure I saw that 'delete thumbnails on exit' somewhere before.  Was thinking of Gwenview, and while it probably was that, it seems to now have a "Low resource usage mode". which deletes the whole thumbnails directory (they do note that even other applications use it).

There are also some history features that can be disabled (no recent files and such I guess).  I always like to disable those, too, because I never use such features in anything for some reason.  I guess it's similar to 'files just laying around, unused'.  (Some probably like those settings for privacy reasons, but I'm the only one using the thing so meh.)

**Comment by agaida** [comment]
it turns out to become a real life comedy - ok, serious again - all i want is to have the 'open as' functionality and similar moved from thunmbnails to the main programn - and god damn, i know that i'm stubborn. So nobody must remind or reword it :P

**Comment by tsujan** [comment]
> Some might be concerned about writes on SSDs 

People who worry about writes on SSDs  are the same people who worry about the size of  the thumbnails folder, namely, you and I ;) As for thumbnails folder, I explained why its size can be safely ignored. As for SSD writes, it's a myth -- maybe, very old SSDs should be treated with more care.

> all i want is to have the 'open as' functionality and similar moved from thunmbnails to the main program

It occurred to me too that we might be able to "move" the existing `Open With...`. Should look into it.

**Comment by agaida** [comment]
ok - i was tired about the writing myth some years ago - namely in 2011 or 12 i guess.

I buyed a Vertex II and get a lot of hints how to reduce the writing to it- and all the nice people was right about. I was not - i used this device just as a normal drive. Result: Six years after i grant this poor device a little break - t was my main device in all the years, because it was fast. So it retiered some day and it is highly unlikely that this device is reactivated again. And now the pure facts: 
* A normal SSD device can take up to 3-4 G writes a day - for 4 to 5 years - ok, some cells might fail after 3000-4000 write cycles - but hey ...
* right now i drive some SSDs with wearing protection - and a lot more free space to use - so what
* even if a device will survive five years - damn, it wouldn't have a place in any new system

* so what? :) *

**Comment by tsujan** [comment]
OK, it's easy to add an "Open Image With..." menu, provided by libfm-qt:

![open_width](https://user-images.githubusercontent.com/981076/68904987-c7442280-0754-11ea-95ec-42a5bfc8cbae.png)

But all of libfm-qt's file menu is created (including copy, cut, past, custom actions,…) and only this part of it is shown.

On the other hand, creating *only that part* needs legacy headers of libfm-qt, which isn't acceptable, IMO.

It isn't a big deal because the whole menu is shown inside the thumbnail bar and, after the needed part is shown by "Open Image With...", it'll be deleted.

Showing it without libfm-qt is possible but would have an ugly code.

@agaida, should I make a PR?

**Comment by agaida** [comment]
i don't get the part of legacy headers right now - and if i would place it in a separate menu point if possible and present

**Comment by tsujan** [comment]
>  don't get the part of legacy headers right now

It means files like `/usr/include/libfm-qt/core/legacy/fm-app-info.h`. They shouldn't be used outside libfm-qt.

> and if i would place it in a separate menu point if possible and present

I didn't get this part.

**Comment by tsujan** [comment]
It's also cool because an SVG image can be opened in Inkscape or FeatherPad:

![open_svg](https://user-images.githubusercontent.com/981076/68910277-70dfdf80-0766-11ea-88b2-7c6c0e36640d.png)

The menu may change with the mime type and the menu-item disappears if no image file is opened.

I'm uncertain because although it's nice, simple and complete, creating a whole right-click menu and using only a sub-menu of it doesn't seem like a frugal code.

I think libfm-qt can be changed (in a backward incompatible way) so that creation of the whole libfm-qt's right-click menu won't be needed for this. For now, it's a single case but who knows where it might be used later?

You see, I have doubts ;) Hence asking.

**Comment by agaida** [comment]
```
Package: lximage-qt
Version: 0.14.1-1
Priority: optional
Section: x11
Maintainer: LXQt Packaging Team <pkg-lxqt-devel@lists.alioth.debian.org>
Installed-Size: 346 kB
Depends: libc6 (>= 2.14), libexif12 (>= 0.6.21-1~), libfm-qt6 (>= 0.14.1~), libglib2.0-0 (>= 2.35.9), libqt5core5a (>= 5.11.0~rc1), libqt5dbus5 (>= 5.0.2), libqt5gui5 (>= 5.7.0), libqt5network5 (>= 5.0.2), libqt5printsupport5 (>= 5.0.2), libqt5svg5 (>= 5.6.0~beta), libqt5widgets5 (>= 5.2.0), libqt5x11extras5 (>= 5.6.0), libstdc++6 (>= 5), libx11-6, libxfixes3
Recommends: lximage-qt-l10n, qt5-image-formats-plugins
Homepage: https://github.com/lxqt/lximage-qt
Tag: uitoolkit::qt
Download-Size: 87,9 kB
APT-Sources: http://ftp.debian.org/debian buster/main amd64 Packages
Description: Image viewer for LXQt
 A simple image viewer for LXQt. Additional file formats can be processed if
 one install qt5-image-formats-plugins.
```
^^ so we already use the libfm headers here - it makes no difference which of them we use packagingwise

**Comment by tsujan** [comment]
Packagingwise it doesn't make a difference but, believe me, codewise it does: it would be an ugly and unmaintainable code.

Last night, I made some changes to libfm-qt to test an idea and it worked but, in the end, it felt absurd — a waste of time ;)

All things considered, now I don't think this justifies changing libfm-qt. With the simple PR that I'll make (today or tomorrow), it's **exactly** like right clicking inside the thumbnail view but without thumbnails and without showing the whole menu. The menu is deleted after it's used or left; that's also like the right-click menu. Of course, the user won't know any of this: he/she just opens the menu and then, opens the file in an app/editor of his choice.

All in all, I think I may have given this too much thought and time. My bad!
