### ISSUE TITLE
[enhancement] image number and galery size in status-bar

### ISSUE THREAD

**Issue by pirate486743186** [lxqt/lximage-qt#314]
##### Expected Behavior

You should be able to quickly read the number of the image, and the number of images contained in the gallery, in the status-bar. For example "5 of 32", meaning the fifth image in the gallery containing 32 images.

##### Current Behavior

The status-bar is completely empty.

**Comment by tsujan** [comment]
Currently, lximage-qt doesn't remember the last file sorting the user has given to it. So, "X of Y" should wait. But we other plans for the status-bar.

**Comment by pirate486743186** [comment]
Well, what ever you see in the thumbnails list?

**Comment by tsujan** [comment]
Yes. For now, it has libfm-qt's default sorting and isn't remembered from session to session. Syncing it with pcmanfm-qt is not an option.

**Comment by tsujan** [comment]
Now, the status bar isn't empty (→ https://github.com/lxqt/lximage-qt/pull/315#issuecomment-619813529).

Gallery size and `X of Y` can't be added because (1) the status bar has no space left, (2) There is no gallery but files called images that are among other files, and (3) their order isn't pre-determined, especially when seen inside a file-manager.
