### ISSUE TITLE
[Enhancement] Color management support

### ISSUE THREAD

**Issue by nvmnghia** [lxqt/lximage-qt#320]
Add support for color management.

##### Expected Behavior

Support both embedded and system monitor profile. Given that the whole Lubuntu environment doesn't support color management out of the box, I suggest that LXImage should at least support the embedded color profile.

This [displaycal](http://displaycal.net/icc-color-management-test/) test was used to determine color profile support.

##### Current Behavior

It doesn't support at all, please follow the above link.

##### Possible Solution

I don't know :p

##### Context

I take a lot of photos in DNG, and output to sRGB and DCI-P3 (sometimes AdobeRGB).

##### System Information

* Distribution & Version: Lubuntu 20.04

**Comment by tsujan** [comment]
I have no experience in color management but I know that Qt can get embedded ICC profiles. However, I didn't find a Qt method for applying them.

gwenview has it own codes for it but, as far as I tested, the results were suboptimal.

**Comment by tsujan** [comment]
This report shows that it isn't supported yet: https://bugreports.qt.io/browse/QTBUG-6582

**Comment by HybridDog** [comment]
The main purpose of an image viewer is to display images, so in my personal opinion, color management is a necessary requirement for me to use the software.
In comparison to firefox, eye of gnome and mpv (with `--vo=gpu-next`), lximage-qt shows this image in green:
![image](https://github.com/lxqt/lximage-qt/assets/3192173/933b79a9-eef1-456d-8062-722c5d04618b)

Another necessary requirement for me is [gamma-correct scaling](http://www.ericbrasseur.org/gamma.html?i=2)

Here is a website which may have useful information about color management: https://gitlab.freedesktop.org/pq/color-and-hdr/-/tree/main

> This report shows that it isn't supported yet: https://bugreports.qt.io/browse/QTBUG-6582

The last comment mentions that ICC profiles are supported except the parsing of "printer style color profiles".

**Comment by tsujan** [comment]
The report is open, and we accept PRs.

**Comment by tsujan** [comment]
Not having dealt with color spaces before, I just added `QImage::convertToColorSpace(QColorSpace(QColorSpace::SRgb))` to lximage-qt's code and tested it with a few images which had embedded color profiles, including the image of the previous comment. The result seemed fine (compare the displayed image with its thumbnail):

![embedded](https://github.com/lxqt/lximage-qt/assets/981076/9e27df40-8562-4aa0-9c93-48d75e964a75)

![embedded1](https://github.com/lxqt/lximage-qt/assets/981076/ae09c570-f019-4751-b75c-3101c7fba183)

Then, in the short time I had, I tried `lcms2` by following its documentation. It only showed the first image correctly. However, the reason should be my insufficient or inefficient use of `lcms2` — had never used `lcms2` before.

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/lximage-qt/pull/635

I think it's what can be done with the current support in Qt:

![pr](https://github.com/lxqt/lximage-qt/assets/981076/e955ec50-6caa-43bf-9b30-1836358c2b54)

It worked with the images I found in http://regex.info/blog/photo-tech/color-spaces-page2, but it doesn't work outside Qt's support, of course.

`lcms2` or another tool may be also used, but I couldn't make `lcms2` work with a lot of extra codes.

**Comment by tsujan** [comment]
Also, the following two images look the same here with "sRGB" , but they're different with "None":

![1](https://github.com/lxqt/lximage-qt/assets/981076/a98c1973-cb4c-476c-8d92-e9384b604644)

![2](https://github.com/lxqt/lximage-qt/assets/981076/373d9c72-cfa0-4b3c-a625-481c0d1811cf)

I made the second one with lximage-qt itself, by choosing "Linear sRGB" (but not pressing OK) and saving the reloaded image.

**Comment by stefonarch** [comment]
Looking at this example maybe making "sRGB" default isn't a bad idea (looks like thumbnails get generated with "none"):

![screen_area_lun_21:19:47_](https://github.com/lxqt/lximage-qt/assets/10681413/f2973e3d-c0b9-41a1-b521-03c97b617930)

**Comment by tsujan** [comment]
> maybe making "sRGB" default isn't a bad idea

Will do it. It's as simple as changing a 0 to 1 in the code.

I thought adding "supported by most monitors" might be enough. Since it doesn't cause any overload compared to "None" with ordinary images, it can be the default.

**Comment by HybridDog** [comment]
> For most — or almost all — monitors, "sRGB" is the correct option (the first after "None").

I think this changes in the near future due to new display technology, e.g. oled, quantum dots, etc.. 
Furthermore, the majority of displays may actually use the 2.2 gamma instead of the sRGB EOTF, which is slightly different (very slightly).
Anyways, I think the change, especially the support for embedded colour profiles, is a big improvement. Thanks.
#
Here is an attempt to visualise the difference between 2.2 gamma and sRGB EOTFs using the non-linearity of brightness perception approximated by the OkLAB colourspace. 
![srgb_gamma22_difference_visualisation](https://github.com/lxqt/lximage-qt/assets/3192173/479091bf-3e94-4660-a231-06a69dda76b1)

**Comment by tsujan** [comment]
> I think this changes in the near future due to new display technology, e.g. oled...

Thanks for the info you provided in your both comments!

sRGB seems to be the most acceptable default for now. Qt's options are limited, and the user could change the setting.

As I shortly mentioned in my previous comments, `lcms2` could be used too, so that the user could add any profile file supported by it. But I think such a leap would be too big: from no support to an advanced one. Let's stick with what Qt provides. At least we know it's safe and we won't encounter a crash in an external library (which I encountered).
