### ISSUE TITLE
No shortcut control for existing ones

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lximage-qt#330]
It's possible to add a keyboard shortcut which is already assigned.

##### Expected Behavior

It should ask about whether changing it or not

##### Current Behavior

It get's saved, and no one of both is working. 
While testing this I see another  issues, not sure how or if related:
* the shortcut added shows up at every line in the menu (this and the next one look like **only** true for editing "annotations toolbar shortcut)

![cltr+0](https://user-images.githubusercontent.com/10681413/91998397-729d8280-ed3b-11ea-8082-e638d8288f8f.png)

* it doesn't survive restart (the new shortcut is cleared)
* it is not possibile to remove (clear the field)  for an added shortcut: backspace, cltr+x, esc, canc ecc: all is interpreted as new shortcut.
 
##### Steps to Reproduce (for bugs)

1. Open Preferences > shortcut tab
2. Add for example ctrl+O for Annotations Toolbar
3. Click OK
4. Try to use cltr+0 for opening, not working anymore.

          

##### System Information
Arch, git

**Comment by tsujan** [comment]
> It get's saved, and no one of both is working.

Yes, that's the result of defining an "ambiguous shortcut".

> it doesn't survive restart (the new shortcut is cleared)

If I correctly remember, I didn't add a code for removing ambiguous shortcuts at startup (I've done so in FeatherPad though). I just checked: I created an ambiguous shortcut and it survived app restart.

> it is not possibile to remove (clear the field) for an added shortcut:

It is possible. Use a modifier key, like Shift. This wasn't related to your point.

I haven't seen a shortcut control in many apps -- it seems that the responsibility is the user's -- although I have added it to FeatherPad. It's possible to implement it in lximage-qt but i's also possible to reset ambiguous shortcuts at startup. I'm not sure which way is better (the latter is easier).

**Comment by tsujan** [comment]
BTW, I'll add a tooltip about using modifier keys for clearing the entry -- as is done by a QTerminal contributor but in fewer words.

**Comment by stefonarch** [comment]
To be more clear: 

* the not saving issue and the visual glitch is true _only_ for the "annotations toolbar" shortcut, if ambiguous or not.

* Other ambigous shortcuts get saved also on restart and end up not working.

**Comment by tsujan** [comment]
> the not saving issue and the visual glitch is true only for the "annotations toolbar" shortcut,

So strange! Should look into the code. Thanks!

**Comment by stefonarch** [comment]
Maybe we should separate those issues, there aren't related probably.

**Comment by tsujan** [comment]
> Maybe we should separate those issues, there aren't related probably.

Yes.

Let me first to reread the code. I'll be busy for a few days but will do it afterward.

**Comment by tsujan** [comment]
Today, I took a look at the code and was really lucky to find the problem of annotation toolbar quickly. It was exactly as you described.

The rest (shortcut control) was easy because I just had to modify the code that I already had in FeatherPad. The difference is that lximage-qt prevents the user from creating ambiguous shortcuts.

So, the PR is ready for your tests: https://github.com/lxqt/lximage-qt/pull/331

**Comment by stefonarch** [comment]
Works fine, I see annotations toolbar has disappeared from the shortcuts.
There was an ambiguous shortcut saved and it warned about it, ok, but this is probably rare, because it doesn't allow the saving of those anymore. 

The only   problem I see is that the red warning about "not saving it" is activated when editing only one shortcut at clicking "ok"  so it's visible for just a fracture of a second, unless you hold down on "ok".

**Comment by tsujan** [comment]
Thanks for testing.

> The only problem I see is that the red warning about "not saving it" is activated when editing only one shortcut at clicking "ok"

I didn't understand this. Please be more specific. There are 2 kinds of warnings:

 * One is temporary and says, "Ambiguous shortcut not accepted," which means the shortcut isn't changed because the typed shortcut was ambiguous.
 * The other is rare and permanent, appears only when there's an ambiguous shortcut from a previous version, and says, "Warning: Ambiguous shortcut detected!".

Which one do you mean and what is the problem?

**Comment by tsujan** [comment]
I cannot reproduce it. Please:

 1. Attach your `~/.config/lximage-qt/settings.conf` as a zipped file to your next comment.
 2. Tell me exactly how I can reproduce the issue (step by step: 1, 2, ...).

**Comment by stefonarch** [comment]
Doesn't depend on settings IMHO

1) go to the shortcuts tab
2) edit an empty field with cltr+o (already present)
3) click ok button

The red warning is seen but so fast that no one can read it because the window closes.

**Comment by stefonarch** [comment]
> If you want to see it for 2.5 seconds, you should press `Enter` after typing `Cltr+O`.
or hold down on ok for longer time. Fact is the user knows there was something but not what :)

**Comment by tsujan** [comment]
It's logical that if the user wants to know it, he shouldn't close the window by pressing OK. But, first, there's nothing serious to know (the important thing is the result ) and, second, adding a message box instead of a clean warning bar to prevent closing would be not only ugly but also annoying, IMO.

**Comment by tsujan** [comment]
BTW, I updated lximage-qt's translations right now.
