### ISSUE TITLE
Open new image in foreground always

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lximage-qt#427]
When one  image is opened clicking another one in the file manager  it does not open in foreground but as second instance in task manager in the panel.
##### Expected Behavior

Clicking an image it opens in foreground always.
##### Current Behavior

If already one is opened it doesn't but needs a second click at guess in the task manager. Worse if already many pics are opened.
##### Possible Solution

An "allow only one instance" setting in lximage-qt?
##### Steps to Reproduce (for bugs)

as above

* Distribution & Version:  all

**Comment by tsujan** [comment]
lximage-qt is already a single-instance app. You probably meant a "single-window app" but that wouldn't affect what you see either.

Window managers have what is called "focus stealing prevention". Overriding it in apps is almost impossible. You might want to change it in the WM you use but you might see undesirable effects in other apps.

A word about my personal experience with overriding "focus stealing prevention":

Years ago, I tried my best to do it in FeatherNotes because I got angry when its window didn't come up when I clicked its tray icon ;) At last, I succeeded in doing it by using some tricks but, later, I found out that if I changed the degree of "focus stealing prevention" in KWin, the same thing would happen again. So, I accepted my (partial) failure.

**Comment by tsujan** [comment]
The best that I (or anyone else) could do will be using the above-mentioned tricks that I found in the case of FeatherNotes. They work only under X11 (Wayland ignores everything about window positioning or raising) and not under all circumstances.

If you agree, please changes the title to something like "try to open in foreground"; if not, I'm afraid a single-window mode wouldn't solve any problem and would hassle be a hassle, not a feature.

**Comment by stefonarch** [comment]
Maybe you're right about the single instance, now I'm going through the other viewers in Qt and else, atm none has that but all of them open  newly clicked images in foreground.

**Comment by tsujan** [comment]
> atm none has that but all of them open newly clicked images in foreground.

With the PR I'll make, lximage-qt will do that in situations that they don't ;)

**Comment by tsujan** [comment]
This patch steals the focus forcefully: https://github.com/lxqt/lximage-qt/pull/428

**Comment by stefonarch** [comment]
Works, thanks! :)
