### ISSUE TITLE
Space and backspace doesn't work as shortcuts for next/previous image

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lximage-qt#475]
##### Expected Behavior

As user can assign them, they should work
##### Current Behavior

They are shown in "shortcuts" instead of `> <` but are not working.
##### Possible Solution

Make them work (best) or don't make it possible to select them.
##### Steps to Reproduce (for bugs)

1.Assign space for next and backspace for previous image in Preferences > Shortcuts
2. Close and open lximage-qt
3. try using them
4. only  `> <`  working

##### Context

Those shortcuts are often used to  go through files, examples are darktable, digikam
##### System Information

* LXimage-qt version: git, all

**Comment by tsujan** [comment]
Thanks!

Space, Backspace and a few other shortcuts are hard-coded (Space → next image, Backspace → previous image,...). When they're defined explicitly by the user, I guess they become ambiguous.

I'll look into them later. For now, I'm testing a vast code cleanup. Separate commits were added in previous months, without considering their relations to each other, and that has cluttered the code (and also introduced some bugs).

**Comment by tsujan** [comment]
This can be fixed by defining/updating hard-coded shortcuts after custom shortcuts are set and not duplicating the latter. I wrote the needed code and it worked.

Since I have a considerable amount of changes that aren't committed yet, the order of committing will be this:

 1. Merging https://github.com/lxqt/lximage-qt/pull/474
 2. Making a PR for https://github.com/lxqt/lximage-qt/issues/473 and merging it.
 3. Making a PR for https://github.com/lxqt/lximage-qt/issues/477 and merging it.
 4. Making a PR for the current issue and merging it.

**Comment by stefonarch** [comment]
They should both also be listed by default.

**Comment by tsujan** [comment]
> They should both also be listed by default.

They can't be listed in the shortcut editor because they aren't assigned to any action — they're hard-coded into the window itself.

Maybe a "Hidden Shortcuts" dialog. But it isn't so important because all shortcuts that the user may need can be assigned by him in the shortcut editor.

**Comment by tsujan** [comment]
Oh, and there are 5 of them, not 2.
