### ISSUE TITLE
[Screenshot] When using "Capture an area of the screen" on a monitor not on topleft position (not 0,0 coordinates) you can't select area.

### ISSUE THREAD

**Issue by slidinghotdog** [lxqt/lximage-qt#522]
Happens on my desktop when using the bottom screen, replicated on VirtualBox with openbox, xfwm4 and kwin_x11, see video:

https://user-images.githubusercontent.com/33790211/148850960-e6091b9c-03f3-4ada-9e39-7b88c005d624.mp4

##### Expected Behavior

Should be able to select area in any screen.

##### Current Behavior

Can only select area from topleft screen

##### Possible Solution

- area selection dialog (the one that contains the first screenshot which is then used to select the area) covers all screens and lets you select anywhere.
- area selection dialog shows only current screen (same current behaviour but with correct screen).

##### Steps to Reproduce (for bugs)

1. have 2 or more monitors (or add Display on VirtualBox)
2. open lximage-qt and drag it to a monitor that's not on 0,0 coordinates
3. select option "Capture an area of the screen"
4. click OK

##### System Information

* LXimage-qt version: lximage-qt 1.0.0-1
* Distribution & Version: Archlinux
* Qt Version: qt5-base 5.15.2+kde+r277-1
* liblxqt Version: liblxqt 1.0.0-1

**Comment by tsujan** [comment]
lximage-qt's screenshot code won't be developed and might be removed. See `lximage-qt --help`.

If you see the same problem in screengrab, please open an issue for it.

**Comment by slidinghotdog** [comment]
> If you see the same problem in screengrab, please open an issue for it.

Didn't know about Screengrab, it works fine there.


> lximage-qt's screenshot code won't be developed and might be removed. See lximage-qt --help.

So no PR for it will be accepted? I have a  quickfix for it, change:
https://github.com/lxqt/lximage-qt/blob/12d299bdec7ecfe357092d5dc2451bbdb4bbc155/src/screenshotselectarea.cpp#L38
to:
```
  setWindowFlags(Qt::FramelessWindowHint | Qt::WindowStaysOnTopHint | Qt::X11BypassWindowManagerHint);
  setGeometry(image.rect());
```

**Comment by tsujan** [comment]
> So no PR for it will be accepted? I have a quickfix for it, change:

Some LXQt members think that the code should be removed; some others (me included) think that it can be left as it is but with a warning (as in `--help`). The first group is right in saying that screengrab is LXQt's screenshot utility and we shouldn't have parallel functionalities. The second group (I think Alf agreed with me) say that we shouldn't annoy users by removing what they've got used to.

Since you've found a simple fix for the problem, I see no reason why it shouldn't be merged.

> also, should data/lximage-qt-screenshot.desktop.in be removed if it's deprecated?

Good idea! We could keep the code (for now) and remove `lximage-qt-screenshot.desktop` instead.

Would you please make 2 PRs, one for the fix and the other for removing the desktop entry? Sorry for the confusion!

**Comment by slidinghotdog** [comment]
> Would you please make 2 PRs, one for the fix and the other for removing the desktop entry? Sorry for the confusion!

Ok, done.

**Comment by tsujan** [comment]
Thanks!
